### ISSUE TITLE
Allow users to select multiple watersheds

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Watershed#8]
1. Reconfigure the notebook to allow selecting more than one watershed from a state. It's not entirely clear to me how this would work effectively. Currently we provide users the option of selecting their watershed of interest through a dropdown menu. That doesn't work for multiple selections. Could we do checkboxes?
2. Reconfigure the notebook to display results for each selected watershed. Would we show these separately (easy, we've already done this for the congressional districts) or summed together (maybe even easier actually)?

**Comment by shansen5** [comment]
There is a SelectMultiple widget that handles this pretty well.  Ctrl-click adds to the selection, Shift-click extends the selection.  I'm putting it into the notebook.  I'll modify the DataSet behavior to account for a list of huc8s instead of just one.

**Comment by shansen5** [comment]
This is done in the latest push to the add-DMR-code-blocks branch.
Currently it is showing all results together, not separately by watershed.  It is allowing selection of multiple watersheds, selecting multiple facilities within the selected watersheds, and selecting multiple pollutants discharged by the selected facilities.
We'll need to decide how the data should be aggregated.
The code blocks will be documented with markdown cells describing the selection soon.

**Comment by Frijol** [comment]
relevant PR: https://github.com/edgi-govdata-archiving/ECHO-Watershed/pull/7
